### ISSUE TITLE
An update is required!

### ISSUE THREAD

**Issue by Color-maN** [Freddywhest/NotPixel#11]
The creators of Hot Pixel often release posts on their channel about bots and pixel chaos. Due to the new update, a feature for painting pixels according to a template is required.

1) The user will receive 3 times more points per pixel.

2) The bot will become much safer.

Freddy, please do this, we will all be very grateful to you!

**Comment by Color-maN** [comment]
Пытался сделать через запросы WebSocket, но сталкиваюсь с ошибкой axios. Есть файл picture.txt, содержащий в себе все id и их цвета hex для главного рисунка. Суть работы была в получении обновленных данных пикселей и сравнении их с данными пикселями рисунка. Может быть кто доработает :)

I tried to do it through WebSocket requests, but I encounter an axios error. There is a file picture.txt , containing all the IDs and their hex colors for the main drawing. The essence of the work was to obtain updated pixel data and compare it with the given pixels of the drawing. Maybe someone will finalize it :)
Вот файлы, где были изменения.
[picture.txt](https://github.com/user-attachments/files/17342298/picture.txt)
[api.txt](https://github.com/user-attachments/files/17342311/api.txt)
[tapper.txt](https://github.com/user-attachments/files/17342312/tapper.txt)

**Comment by Freddywhest** [comment]
Can you share a picture of the axios error you get

**Comment by Color-maN** [comment]
> Можете ли вы поделиться фотографией ошибки axios, которую вы получаете

![{E1CBA49B-21FC-4F25-82EF-529B8B773D1C}](https://github.com/user-attachments/assets/24826bc9-c7c2-427f-a111-48a61213e8e4)

**Comment by Freddywhest** [comment]
Send me a picture of your line 164 - 170 of your api.js and 465-475 of tapper.js

**Comment by Freddywhest** [comment]
Also, scroll down to the last bottom of the error and send me a picture

**Comment by Freddywhest** [comment]
By the way how did you get the picture.txt?

**Comment by Freddywhest** [comment]
Fixed

**Comment by Color-maN** [comment]
> Кстати, как вы получили picture.txt?

I used DevTools for Telegram Desktop, checked the application's network requests that contain photos. One of them had a photo of the main template. I downloaded a photo in .png format, and then worked with Python to get pixels with the Pillow library.
[ProjPy.zip](https://github.com/user-attachments/files/17347038/ProjPy.zip)
