### ISSUE TITLE
No 3x points? 

### ISSUE THREAD

**Issue by ali578745** [Freddywhest/NotPixel#12]
only got 90 px from 24 repaints :((

**Comment by Color-maN** [comment]
> из 24 перерисовок получилось только 90 пикселей :((

Hello, user! The new bot is made in such a way that it can get additional pixels (+8) to draw on the canvas, but because of the invented code, it does not always have time to color the desired pixel, since code processing also takes time, and during this time another user can repaint it. And for that matter, it draws a regular pixel. Look at the benefits of this, but it doesn't look like a bot) In general, he alternates, do not pay attention.

**Comment by Freddywhest** [comment]
> > из 24 перерисовок получилось только 90 пикселей :((
> 
> Hello, user! The new bot is made in such a way that it can get additional pixels (+8) to draw on the canvas, but because of the invented code, it does not always have time to color the desired pixel, since code processing also takes time, and during this time another user can repaint it. And for that matter, it draws a regular pixel. Look at the benefits of this, but it doesn't look like a bot) In general, he alternates, do not pay attention.

Good explanation bro, I don't know what they ment by 3x

**Comment by Color-maN** [comment]
> Хорошее объяснение, чувак, я не знаю, что они имели в виду под 3x

Человек который открыл проблему #7 писал, что можно получить X3, я тоже так начал думать и писать также, только потом, когда я сам открыл приложение Not Pixel, понял что это не X3, а +8 баллов.

При этом увидел в канале Telegram, что кто то пишет про проблемы с X3, такое впечатление, что люди вообще даже не открывали руками само приложение, и не видели, что награда зависит ещё от уровня upgrade.

**Comment by Color-maN** [comment]
> > Хорошее объяснение, чувак, я не знаю, что они имели в виду под 3x
> 
> Человек, открывший задачу [№7,](https://github.com/Freddywhest/NotPixel/issues/7) написал, что можно получить X3, я тоже так начал думать и писать, только потом, когда я сам открыл приложение Not Pixel, понял, что это не X3, а +8 баллов.

При этом увидел в канале Telegram, что кто то пишет про проблемы с X3, как будто люди вообще даже не открывали руками само приложение, и не видели, что награда зависит ещё от уровня upgrade.
