### ISSUE TITLE
Getting user unauthorised 

### ISSUE THREAD

**Issue by b4uheart** [Freddywhest/NotPixel#4]
| rahul | ⚠️ Error while getting user info: access unauthorized after running for about 15 min it stuck on this even after using sessions. And even on idle it stays like [2024-10-02 10:27:30] | INFO | [notpixel] | kak | Sleeping for 27 seconds...
[2024-10-02 10:27:31] | INFO | [notpixel] | pap | Balance: 183.92092816667PX
[2024-10-02 10:27:31] | INFO | [notpixel] | pap | Sleeping for 26 seconds...
[2024-10-02 10:27:31] | INFO | [notpixel] | unknown | Balance: 73.12979899999699PX no paint is happening

**Comment by Freddywhest** [comment]
Get a new query id every 10mins

**Comment by b4uheart** [comment]
But I am using sessions

**Comment by Freddywhest** [comment]
Fixed

**Comment by toastyy00** [comment]
please make it simple when entering a query, it's a bit difficult if use json format, it's better to use .txt and ignore the use of the name. thank you

**Comment by Freddywhest** [comment]
That's the only thing I can do and it's the same as .txt. You have to get use to it
