### ISSUE TITLE
Painting on canvas

### ISSUE THREAD

**Issue by Color-maN** [Freddywhest/NotPixel#5]
I would like to know how the drawing system works, if I knew more about programming languages, I would look at it myself, but I'm not very smart, so I want to ask.

Does the bot draw pixels randomly or is it trying to draw a given picture?

And if it's chaotic, will it be possible to make an update in the future that will allow the bot to draw a given picture?

**Comment by Freddywhest** [comment]
No, I can't make a bot to draw a specific picture. I don't even draw a specific picture when I play the game by myself
