### ISSUE TITLE
UPGRADE & painting

### ISSUE THREAD

**Issue by Color-maN** [Freddywhest/NotPixel#6]
Возникла проблема с рисованием. При запуске бот сначала пытается собрать вознаграждение, а только потом рисовать, в результате рисование не используется до получения вознаграждения. Ценные баллы теряются.

И можно ли будет добавить возможность настраивать улучшения (boosts) в ближайшем будущем?

И еще вопрос, если не тяжело ответить, понимаю что раздел для ошибок. Со стороны сервера Not Pixel, нет подозрений к тому, что бот подключается каждые 200-700 секунд? Как будто человек-пользователь не спит?

**Comment by Freddywhest** [comment]
So you have an option to set the sleep time to whatever time you want

**Comment by Color-maN** [comment]
А что с рисованием? Почему бот почти не рисует. Например на сессии доступно 9 покрасок пикселей, бот загружает сессию. Время остановки вознаграждения еще не подошло к концу, но забрать его можно, а бот не забирает вознаграждение и отказывается рисовать доступные пиксели.

И можно ли будет добавить возможность настраивать улучшения (boosts) в ближайшем будущем?

**Comment by Color-maN** [comment]
С рисованием я разобрался. Проблема была в том, что в файле tapper.js, код выполняющий рисование, входил в условие для кода, который выполняет задания. Зачем так сделано, если в .env и так есть параметр AUTO_PAINT, непонятно.

И остается один вопрос. Можно ли будет добавить возможность настраивать улучшения (boosts) в ближайшем будущем?

**Comment by amirnajm** [comment]
> I figured out how to draw. The problem was that in the tapper.js file, the code that performs drawing was included in the condition for the code that performs tasks. It is unclear why this is done if the AUTO_PAINT parameter is already present in .env.
> 
> And one question remains: Will it be possible to add the ability to customize boosts in the near future?

hello sir can you share the solotion for this?how to fix

**Comment by Color-maN** [comment]
> здравствуйте, сэр, можете поделиться решением этой проблемы?как исправить

По пути NotPixel-main\bot\core\ замените следующие файлы: [tappers.zip](https://github.com/user-attachments/files/17258643/tappers.zip)

И не забудьте увеличить время запросов начиная от 65 секунд и больше, лучше вообще от 8 часов.

**Comment by amirnajm** [comment]
> > hello sir can you share the solution to this problem?how to fix
> 
> In the path NotPixel-main\bot\core\ replace the following files: [tappers.zip](https://github.com/user-attachments/files/17258643/tappers.zip)
> 
> And don't forget to increase the query time starting from 65 seconds and more, better yet from 8 hours.

where is this query time starting i didnt find it sir

**Comment by Color-maN** [comment]
> с чего начинается этот запрос, я не нашел его, сэр

В вашем .env файле должен быть настроен параметр SLEEP_BETWEEN_REQUESTS=[65,142], а лучше SLEEP_BETWEEN_REQUESTS=[27976,31463], так более безопасно.

**Comment by amirnajm** [comment]
> > where does this query start i didn't find it sir
> 
> In your .env file, the parameter SLEEP_BETWEEN_REQUESTS=[65,142] should be set, or better yet, SLEEP_BETWEEN_REQUESTS=[27976,31463], it's safer.

thnak you again sir
